// <auto-generated />
using AppJZ.Data;
using System;
using AppJZ.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppJZ.Migrations.Aulalink
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251204172905_UpdateAulalinkSchema")]
    partial class UpdateAulalinkSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AppJZ.Models.Actividadevaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int?>("TipoActividadId")
                        .HasColumnType("int(11)")
                        .HasColumnName("tipo_actividad_id");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int(11)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TipoActividadId" }, "tipo_actividad_id");

                    b.HasIndex(new[] { "UsuarioId" }, "usuario_id");

                    b.ToTable("actividadevaluacion", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Administracionescolar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DocenteId")
                        .HasColumnType("int(11)")
                        .HasColumnName("docente_id");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int(11)")
                        .HasColumnName("estudiante_id");

                    b.Property<int?>("GradoId")
                        .HasColumnType("int(11)")
                        .HasColumnName("grado_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DocenteId" }, "docente_id");

                    b.HasIndex(new[] { "EstudianteId" }, "estudiante_id");

                    b.HasIndex(new[] { "GradoId" }, "grado_id");

                    b.ToTable("administracionescolar", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Bibliotecaalmacen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int(11)")
                        .HasColumnName("cantidad");

                    b.Property<bool?>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("disponible")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("NombreMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_material");

                    b.Property<int?>("TipoMaterialId")
                        .HasColumnType("int(11)")
                        .HasColumnName("tipo_material_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TipoMaterialId" }, "tipo_material_id");

                    b.ToTable("bibliotecaalmacen", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Datosadicionale", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int(11)")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Direccion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("direccion");

                    b.Property<int?>("Grado")
                        .HasColumnType("int(20)")
                        .HasColumnName("grado");

                    b.Property<string>("NombreAcudiente")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_acudiente");

                    b.Property<string>("NumeroAcudiente")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numero_acudiente");

                    b.Property<int?>("ParentescoId")
                        .HasColumnType("int(11)")
                        .HasColumnName("parentesco_id");

                    b.Property<string>("Telefono")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("telefono");

                    b.HasKey("UsuarioId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Grado" }, "grado");

                    b.HasIndex(new[] { "ParentescoId" }, "parentesco_id");

                    b.ToTable("datosadicionales", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("docente", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Documentacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int?>("TipoDocumentoId")
                        .HasColumnType("int(11)")
                        .HasColumnName("tipo_documento_id");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int(11)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TipoDocumentoId" }, "tipo_documento_id");

                    b.HasIndex(new[] { "UsuarioId" }, "usuario_id")
                        .HasDatabaseName("usuario_id1");

                    b.ToTable("documentacion", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Efmigrationshistory", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("MigrationId")
                        .HasName("PRIMARY");

                    b.ToTable("__efmigrationshistory", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Formulario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("NumeroDocumento")
                        .HasColumnType("int(11)")
                        .HasColumnName("numero_documento");

                    b.Property<int>("RolId")
                        .HasColumnType("int(11)")
                        .HasColumnName("rol_id");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int(11)")
                        .HasColumnName("tipo_documento_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RolId" }, "rol_id");

                    b.HasIndex(new[] { "TipoDocumentoId" }, "tipo_documento_id")
                        .HasDatabaseName("tipo_documento_id1");

                    b.ToTable("formulario", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Gestionacademica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GruposTrabajo")
                        .HasColumnType("text")
                        .HasColumnName("grupos_trabajo");

                    b.Property<string>("RegistrarActividades")
                        .HasColumnType("text")
                        .HasColumnName("registrar_actividades");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int(11)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UsuarioId" }, "usuario_id")
                        .HasDatabaseName("usuario_id2");

                    b.ToTable("gestionacademica", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Grado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Creditos")
                        .HasColumnType("int(11)");

                    b.Property<int?>("DocenteId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nivel")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("DocenteId");

                    b.ToTable("grado", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Gradomaterium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GradoId")
                        .HasColumnType("int(11)")
                        .HasColumnName("grado_id");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int(11)")
                        .HasColumnName("materia_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "GradoId", "MateriaId" }, "grado_id")
                        .IsUnique()
                        .HasDatabaseName("grado_id1");

                    b.HasIndex(new[] { "MateriaId" }, "materia_id");

                    b.ToTable("gradomateria", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Materium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("materia", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Matriculafinanza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("FechaPago")
                        .HasColumnType("date")
                        .HasColumnName("fecha_pago");

                    b.Property<bool?>("Matricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("matricula")
                        .HasDefaultValueSql("'0'");

                    b.Property<bool?>("Pension")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("pension")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int(11)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UsuarioId" }, "usuario_id")
                        .HasDatabaseName("usuario_id3");

                    b.ToTable("matriculafinanzas", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Observadoralumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Docente")
                        .HasColumnType("int(11)")
                        .HasColumnName("docente");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("observaciones");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int(11)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Docente" }, "docente");

                    b.HasIndex(new[] { "UsuarioId" }, "usuario_id")
                        .HasDatabaseName("usuario_id4");

                    b.ToTable("observadoralumno", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Parentesco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("parentesco", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Periodoacademico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("periodoacademico", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Tipoactividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("tipoactividad", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Tipodocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("tipodocumento", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Tipodocumentoacademico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("tipodocumentoacademico", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Tipomaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("tipomaterial", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("contraseña");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numero_documento");

                    b.Property<int>("RolId")
                        .HasColumnType("int(11)")
                        .HasColumnName("rol_id");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int(11)")
                        .HasColumnName("tipo_documento_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NumeroDocumento" }, "numero_documento")
                        .IsUnique();

                    b.HasIndex(new[] { "RolId" }, "rol_id")
                        .HasDatabaseName("rol_id1");

                    b.HasIndex(new[] { "TipoDocumentoId" }, "tipo_documento_id")
                        .HasDatabaseName("tipo_documento_id2");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("AppJZ.Models.Actividadevaluacion", b =>
                {
                    b.HasOne("AppJZ.Models.Tipoactividad", "TipoActividad")
                        .WithMany("Actividadevaluacions")
                        .HasForeignKey("TipoActividadId")
                        .HasConstraintName("actividadevaluacion_ibfk_1");

                    b.HasOne("AppJZ.Models.Usuario", "Usuario")
                        .WithMany("Actividadevaluacions")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("actividadevaluacion_ibfk_2");

                    b.Navigation("TipoActividad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppJZ.Models.Administracionescolar", b =>
                {
                    b.HasOne("AppJZ.Models.Usuario", "Docente")
                        .WithMany("AdministracionescolarDocentes")
                        .HasForeignKey("DocenteId")
                        .HasConstraintName("administracionescolar_ibfk_1");

                    b.HasOne("AppJZ.Models.Usuario", "Estudiante")
                        .WithMany("AdministracionescolarEstudiantes")
                        .HasForeignKey("EstudianteId")
                        .HasConstraintName("administracionescolar_ibfk_3");

                    b.HasOne("AppJZ.Models.Grado", "Grado")
                        .WithMany("Administracionescolars")
                        .HasForeignKey("GradoId")
                        .HasConstraintName("administracionescolar_ibfk_2");

                    b.Navigation("Docente");

                    b.Navigation("Estudiante");

                    b.Navigation("Grado");
                });

            modelBuilder.Entity("AppJZ.Models.Bibliotecaalmacen", b =>
                {
                    b.HasOne("AppJZ.Models.Tipomaterial", "TipoMaterial")
                        .WithMany("Bibliotecaalmacens")
                        .HasForeignKey("TipoMaterialId")
                        .HasConstraintName("bibliotecaalmacen_ibfk_1");

                    b.Navigation("TipoMaterial");
                });

            modelBuilder.Entity("AppJZ.Models.Datosadicionale", b =>
                {
                    b.HasOne("AppJZ.Models.Grado", "GradoNavigation")
                        .WithMany("Datosadicionales")
                        .HasForeignKey("Grado")
                        .HasConstraintName("datosadicionales_ibfk_3");

                    b.HasOne("AppJZ.Models.Parentesco", "Parentesco")
                        .WithMany("Datosadicionales")
                        .HasForeignKey("ParentescoId")
                        .HasConstraintName("datosadicionales_ibfk_2");

                    b.HasOne("AppJZ.Models.Usuario", "Usuario")
                        .WithOne("Datosadicionale")
                        .HasForeignKey("AppJZ.Models.Datosadicionale", "UsuarioId")
                        .IsRequired()
                        .HasConstraintName("datosadicionales_ibfk_1");

                    b.Navigation("GradoNavigation");

                    b.Navigation("Parentesco");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppJZ.Models.Documentacion", b =>
                {
                    b.HasOne("AppJZ.Models.Tipodocumentoacademico", "TipoDocumento")
                        .WithMany("Documentacions")
                        .HasForeignKey("TipoDocumentoId")
                        .HasConstraintName("documentacion_ibfk_1");

                    b.HasOne("AppJZ.Models.Usuario", "Usuario")
                        .WithMany("Documentacions")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("documentacion_ibfk_2");

                    b.Navigation("TipoDocumento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppJZ.Models.Formulario", b =>
                {
                    b.HasOne("AppJZ.Models.Rol", "Rol")
                        .WithMany("Formularios")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("formulario_ibfk_2");

                    b.HasOne("AppJZ.Models.Tipodocumento", "TipoDocumento")
                        .WithMany("Formularios")
                        .HasForeignKey("TipoDocumentoId")
                        .IsRequired()
                        .HasConstraintName("formulario_ibfk_1");

                    b.Navigation("Rol");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("AppJZ.Models.Gestionacademica", b =>
                {
                    b.HasOne("AppJZ.Models.Usuario", "Usuario")
                        .WithMany("Gestionacademicas")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("gestionacademica_ibfk_1");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppJZ.Models.Grado", b =>
                {
                    b.HasOne("AppJZ.Models.Docente", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .HasConstraintName("grado_ibfk_docente");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("AppJZ.Models.Gradomaterium", b =>
                {
                    b.HasOne("AppJZ.Models.Grado", "Grado")
                        .WithMany("Gradomateria")
                        .HasForeignKey("GradoId")
                        .IsRequired()
                        .HasConstraintName("gradomateria_ibfk_1");

                    b.HasOne("AppJZ.Models.Materium", "Materia")
                        .WithMany("Gradomateria")
                        .HasForeignKey("MateriaId")
                        .IsRequired()
                        .HasConstraintName("gradomateria_ibfk_2");

                    b.Navigation("Grado");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("AppJZ.Models.Matriculafinanza", b =>
                {
                    b.HasOne("AppJZ.Models.Usuario", "Usuario")
                        .WithMany("Matriculafinanzas")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("matriculafinanzas_ibfk_1");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppJZ.Models.Observadoralumno", b =>
                {
                    b.HasOne("AppJZ.Models.Usuario", "DocenteNavigation")
                        .WithMany("ObservadoralumnoDocenteNavigations")
                        .HasForeignKey("Docente")
                        .HasConstraintName("observadoralumno_ibfk_2");

                    b.HasOne("AppJZ.Models.Usuario", "Usuario")
                        .WithMany("ObservadoralumnoUsuarios")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("observadoralumno_ibfk_1");

                    b.Navigation("DocenteNavigation");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppJZ.Models.Usuario", b =>
                {
                    b.HasOne("AppJZ.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("usuario_ibfk_2");

                    b.HasOne("AppJZ.Models.Tipodocumento", "TipoDocumento")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoDocumentoId")
                        .IsRequired()
                        .HasConstraintName("usuario_ibfk_1");

                    b.Navigation("Rol");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("AppJZ.Models.Grado", b =>
                {
                    b.Navigation("Administracionescolars");

                    b.Navigation("Datosadicionales");

                    b.Navigation("Gradomateria");
                });

            modelBuilder.Entity("AppJZ.Models.Materium", b =>
                {
                    b.Navigation("Gradomateria");
                });

            modelBuilder.Entity("AppJZ.Models.Parentesco", b =>
                {
                    b.Navigation("Datosadicionales");
                });

            modelBuilder.Entity("AppJZ.Models.Rol", b =>
                {
                    b.Navigation("Formularios");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AppJZ.Models.Tipoactividad", b =>
                {
                    b.Navigation("Actividadevaluacions");
                });

            modelBuilder.Entity("AppJZ.Models.Tipodocumento", b =>
                {
                    b.Navigation("Formularios");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AppJZ.Models.Tipodocumentoacademico", b =>
                {
                    b.Navigation("Documentacions");
                });

            modelBuilder.Entity("AppJZ.Models.Tipomaterial", b =>
                {
                    b.Navigation("Bibliotecaalmacens");
                });

            modelBuilder.Entity("AppJZ.Models.Usuario", b =>
                {
                    b.Navigation("Actividadevaluacions");

                    b.Navigation("AdministracionescolarDocentes");

                    b.Navigation("AdministracionescolarEstudiantes");

                    b.Navigation("Datosadicionale");

                    b.Navigation("Documentacions");

                    b.Navigation("Gestionacademicas");

                    b.Navigation("Matriculafinanzas");

                    b.Navigation("ObservadoralumnoDocenteNavigations");

                    b.Navigation("ObservadoralumnoUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
